# This file is part of the pclp_juliet_a distribution.
# Copyright (c) 2024 Igor Marinescu (igor.marinescu@gmail.com).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
""" pclp_out_interpreter_src - interprets the results generated by pclint.
    __init__ function
"""
import sys
from .pclp_out_interpret import PclpInterpreter

#-------------------------------------------------------------------------------
def main():
    """ Init function called when the module is invoked direct from command line:

        > cd "scripts"
        > python -m pclp_out_interpret_src <pclp_out_file>
    """
    print('pclp_out_interpret::__init__.main()')

    retcode = 0

    if len(sys.argv) > 1:
        interpreter = PclpInterpreter()
        res = interpreter.process_file(sys.argv[1])
        if not res:
            interpreter.show_modules(sys.stdout)
        else:
            print("Error in file:", res[0], file = sys.stderr)
            print("Error precessing line:", res[1], file = sys.stderr)
            print(res[2], file = sys.stderr)
            retcode = 1

    else:
        print("Nothing to process.")
        print("Specify as argument the file to be analyzed.")

    sys.exit(retcode)
